__title__ = "arcus toolset"
__description__ = "arcus toolset"
__version__ ="0.1"
__author__ = "Justin G. Mitchell"
__author_email__ = "justin@arcuscg.com"
__license__ = "bsd-2-clause"
__copyright__ = "2022 Justin G. Mitchell"